name: Keep Supabase Active

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Supabase Auth Active
        run: |
          curl -X GET "${{ secrets.VITE_GIKEO_SUPABASE_URL }}/auth/v1/health" \
            -H "apikey: ${{ secrets.VITE_GIKEO_SUPABASE_KEY }}" \
            -H "Content-Type: application/json"
          echo "Pinged Supabase Auth at $(date)"
